# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ miso2-gridview ]
  pull_request:
    branches: [ miso2-gridview ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Archive shaded jar
      uses: actions/upload-artifact@v2
      with:
        name: shaded-jar
        path: target/ParticleTrieur.jar
