# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Nightly artifact

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'
        java-package: jdk+fx
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create nightly shaded jar
      run: mv target/ParticleTrieur.jar target/ParticleTrieur-nightly.jar
    - name: Archive shaded jar
      uses: actions/upload-artifact@v2
      with:
        name: nightly
        path: target/ParticleTrieur-nightly.jar
